[0m11:25:49.503571 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF2A026120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF2C95FD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF2C95F9D0>]}


============================== 11:25:49.506914 | 9386edb1-2220-4e31-ace8-7074b4c107a1 ==============================
[0m11:25:49.506914 [info ] [MainThread]: Running with dbt=1.7.19
[0m11:25:49.507959 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Hidzqi Al-baqir\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:26:09.061631 [debug] [MainThread]: Starter project path: C:\Users\Hidzqi Al-baqir\Documents\Belajar_Coding\first_dbt\dbt_venv\Lib\site-packages\dbt\include\starter_project
[0m11:26:09.083315 [info ] [MainThread]: 
Your new dbt project "dbt_hidzqi" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:26:09.084243 [info ] [MainThread]: Setting up your profile.
[0m11:26:12.595610 [debug] [MainThread]: Command `dbt init` succeeded at 11:26:12.595035 after 23.24 seconds
[0m11:26:12.596318 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF25F96520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF2CF08B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF2CEA9BF0>]}
[0m11:26:12.596737 [debug] [MainThread]: Flushing usage events
[0m11:26:28.613899 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002281E466120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022820D7FED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022820D7FB10>]}


============================== 11:26:28.618955 | 8d5a57dd-a72f-4601-b611-582f54108773 ==============================
[0m11:26:28.618955 [info ] [MainThread]: Running with dbt=1.7.19
[0m11:26:28.619776 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Hidzqi Al-baqir\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:26:28.620314 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Hidzqi Al-baqir\Documents\Belajar_Coding\first_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:26:28.621663 [debug] [MainThread]: Command `dbt run` failed at 11:26:28.621482 after 0.16 seconds
[0m11:26:28.622078 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022820C035C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022820DC1910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022820C33AC0>]}
[0m11:26:28.622458 [debug] [MainThread]: Flushing usage events
[0m09:21:44.518077 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278C71E6120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278C9B2FED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278C9B2FB10>]}


============================== 09:21:44.554321 | 786a92a6-9334-4a7a-894e-9b935b2b8a42 ==============================
[0m09:21:44.554321 [info ] [MainThread]: Running with dbt=1.7.19
[0m09:21:44.556604 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Hidzqi Al-baqir\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m09:21:44.557287 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Hidzqi Al-baqir\Documents\Belajar_Coding\first_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:21:44.558472 [debug] [MainThread]: Command `dbt run` failed at 09:21:44.558320 after 0.24 seconds
[0m09:21:44.558814 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278C99B35C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278C9B79910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278C99E3AC0>]}
[0m09:21:44.559121 [debug] [MainThread]: Flushing usage events
[0m11:08:09.087878 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEC281FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEEBBBC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEEBBB9D0>]}


============================== 11:08:09.094265 | a970581e-1e5c-4960-b0b6-eed3cf28a6fb ==============================
[0m11:08:09.094265 [info ] [MainThread]: Running with dbt=1.7.19
[0m11:08:09.095447 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Hidzqi Al-baqir\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:08:09.096007 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Hidzqi Al-baqir\Documents\Belajar_Coding\first_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:08:09.098002 [debug] [MainThread]: Command `dbt run` failed at 11:08:09.097721 after 0.17 seconds
[0m11:08:09.098619 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEEA3F5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEEC15910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEEA73AC0>]}
[0m11:08:09.099280 [debug] [MainThread]: Flushing usage events
[0m09:19:51.680195 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB36491FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB38DCBC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB38DCB9D0>]}


============================== 09:19:51.683984 | 6f4d846e-39c7-4906-bde0-ff517e6ccbca ==============================
[0m09:19:51.683984 [info ] [MainThread]: Running with dbt=1.7.19
[0m09:19:51.684802 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Hidzqi Al-baqir\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:19:51.685370 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Hidzqi Al-baqir\Documents\Belajar_Coding\first_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:19:51.686223 [debug] [MainThread]: Command `dbt docs generate` failed at 09:19:51.686083 after 0.24 seconds
[0m09:19:51.686514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB38C4F5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB38E21910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DB38C83AC0>]}
[0m09:19:51.686776 [debug] [MainThread]: Flushing usage events
[0m09:20:04.171186 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C977551FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C979E9BC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C979E9B9D0>]}


============================== 09:20:04.174893 | 29f2d2ca-129c-4591-b35e-d59de791c048 ==============================
[0m09:20:04.174893 [info ] [MainThread]: Running with dbt=1.7.19
[0m09:20:04.175644 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Hidzqi Al-baqir\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:20:04.176140 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Hidzqi Al-baqir\Documents\Belajar_Coding\first_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:20:04.177191 [debug] [MainThread]: Command `dbt docs generate` failed at 09:20:04.177039 after 0.19 seconds
[0m09:20:04.177479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C979D1F5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C979EF1910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C979D53AC0>]}
[0m09:20:04.177824 [debug] [MainThread]: Flushing usage events
